theme: jekyll-theme-minimal
title: Brody Erlandson
logo: /photoOfMe.jpg
description: |
  Pursuing PhD in Statistics at CSU <br />
  M.S. in Data Science at U of M <br />
  B.S. in Mathematics at EMU

